# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yandex_kassa_key: <%= ENV["KASSA_SECRET_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_userpass: <%= ENV["SENDGRID_USERPASS"] %>
  sendgrid_key: <%= ENV["SENDGRID_KEY"] %>

test:
  domain_name: example.com
  secret_key_base: 4e7fb82b0871f02338fa6dea07088618e270decdce811b12fcad800429084edb164df2772b97125d0bfdf3db5af5f70b32ef1dacf7639726d5c89d2089e76a8c
  sendgrid_key: _k5MFGfoQAGtL_u5-IpiVA
# Do not keep production secrets in the repository,
# instead read values from the environment.

staging:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yandex_kassa_key: <%= ENV["KASSA_SECRET_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_userpass: <%= ENV["SENDGRID_USERPASS"] %>
  sendgrid_key: <%= ENV["SENDGRID_KEY"] %>

production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yandex_kassa_key: <%= ENV["KASSA_SECRET_KEY"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_userpass: <%= ENV["SENDGRID_USERPASS"] %>
  sendgrid_key: <%= ENV["SENDGRID_KEY"] %>